version: "3.8"

services:
###Iniciar página: http://localhost:8880/otrs/index.pl
###Usuário: root@localhost
###Senha: GVYskvEXNPxLcu4V
  znuny:
    image: alderpinto/znuny:7.0.8
    restart: always
    container_name: znuny
    ports:
#      - 443:443
      - 8880:8880
      - 8881:8881
    env_file: .env      
    volumes:
#      - ./letsencrypt:/etc/letsencrypt
#      - ./Config.pm:/opt/otrs/Kernel/Config.pm
      - ./init:/app
      - ./app:/opt/znuny
    depends_on:
      - postgres
  postgres:
###Usuário: znuny
###Senha: QNq6ieatFB9i2niW  
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mjeffomybyov7xffcba6
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: